### ISSUE TITLE
Content overlaps side nav bar as screen width decreases

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy-sphinx-theme#136] opened 2022-03-27 14:56 UTC
### Describe the bug

For narrow windows, the content of the page overlaps the side nav bar. See screenshot below. For sufficiently narrow screens (i.e. mobile), the nav bar stacks vertically above the content so this is not an issue, but there seems to be some intermediate case where this becomes an issue. I've only tested this on Firefox thus far.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/8676141/160287322-080b67d1-5a80-48b2-a249-f3e7bc106eed.png">

**Comment by dstansby** [comment] 2023-05-12 17:39
Hmm, this doesn't happen to me on https://docs.sunpy.org/en/stable/code_ref/index.html - the content moves below the sidebar when the window gets too narrow. Suggest closing if someone else can't reproduce any more?

**Closed** 2023-09-07 08:44 UTC
Labels: Bug
